title: Default
default_field: title
icon: 'far fa-file-alt'
extends: base
sections:
  main:
    title: admin_main
    fields:
      title:
        title: admin_title
        type: text
        size: 12
      content:
        title: admin_content
        type: html
        size: 12
